# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_column='Number', max_length=20, null=True)),
                ('univalence', models.FloatField(blank=True, db_column='Univalence', null=True)),
                ('sensorid', models.IntegerField(blank=True, db_column='SensorId', null=True)),
                ('schoolid', models.IntegerField(blank=True, db_column='SchoolId', null=True)),
                ('checkerid', models.IntegerField(blank=True, db_column='CheckerId', null=True)),
                ('checkername', models.CharField(blank=True, db_column='CheckerName', max_length=20, null=True)),
                ('status', models.IntegerField(db_column='Status', default=4)),
                ('regist_first', models.DateTimeField(blank=True, db_column='regist_first', null=True)),
                ('use_depart', models.CharField(blank=True, db_column='use_depart', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Device',
            },
        ),
        migrations.CreateModel(
            name='DeviceAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(blank=True, db_column='DeviceId', null=True)),
                ('devicenum', models.CharField(blank=True, db_column='DeviceNum', max_length=20, null=True)),
                ('schoolid', models.IntegerField(blank=True, db_column='SchoolId', null=True)),
                ('roomid', models.IntegerField(blank=True, db_column='RoomId', null=True)),
                ('ordernum', models.IntegerField(blank=True, db_column='OrderNum', null=True)),
                ('alarmstart', models.BooleanField(db_column='AlarmStart')),
            ],
            options={
                'db_table': 'DeviceAlarm',
            },
        ),
        migrations.CreateModel(
            name='DeviceGis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('deviceid', models.IntegerField(blank=True, db_column='DeviceId', null=True)),
                ('devicenum', models.CharField(blank=True, db_column='DeviceNum', max_length=20, null=True)),
                ('schoolid', models.IntegerField(blank=True, db_column='SchoolId', null=True)),
            ],
            options={
                'db_table': 'DeviceGis',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(blank=True, db_column='DeviceId', null=True)),
                ('devicenum', models.CharField(blank=True, db_column='DeviceNum', max_length=20, null=True)),
                ('schoolid', models.IntegerField(blank=True, db_column='SchoolId', null=True)),
                ('typeid', models.IntegerField(blank=True, db_column='TypeId', null=True)),
                ('roomid', models.CharField(blank=True, db_column='RoomId', max_length=20, null=True)),
                ('ordernum', models.IntegerField(blank=True, db_column='OrderNum', null=True)),
                ('devicekind', models.CharField(blank=True, db_column='DeviceKind', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('configureinfo', models.CharField(blank=True, db_column='ConfigureInfo', max_length=30, null=True)),
                ('useflag', models.BooleanField(db_column='UseFlag')),
                ('max_use_time', models.IntegerField(blank=True, db_column='max_use_time', null=True)),
            ],
            options={
                'db_table': 'DeviceInfo',
            },
        ),
        migrations.CreateModel(
            name='DeviceToSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensornum', models.CharField(blank=True, db_column='SensorNum', max_length=50, null=True)),
            ],
            options={
                'db_table': 'DeviceToSensor',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(blank=True, db_column='TypeName', max_length=30, null=True)),
            ],
            options={
                'db_table': 'DeviceType',
            },
        ),
        migrations.CreateModel(
            name='DeviceUseRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(blank=True, db_column='DeviceId', null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('rate', models.FloatField(blank=True, db_column='rate', null=True)),
            ],
            options={
                'db_table': 'DeviceUseRate',
            },
        ),
        migrations.CreateModel(
            name='DeviceUseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(blank=True, db_column='DeviceId', null=True)),
                ('schoolid', models.IntegerField(blank=True, db_column='SchoolId', null=True)),
                ('existimage', models.BooleanField(db_column='ExistImage')),
                ('imageaddress', models.CharField(blank=True, db_column='ImageAddress', max_length=40, null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('begintime', models.DateField(blank=True, db_column='BeginTime', null=True)),
                ('endtime', models.DateField(blank=True, db_column='EndTime', null=True)),
            ],
            options={
                'db_table': 'DeviceUseRecord',
            },
        ),
        migrations.CreateModel(
            name='PropertyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(blank=True, db_column='DeviceId', null=True)),
                ('checkerid', models.CharField(blank=True, db_column='CheckerId', max_length=40, null=True)),
                ('checkername', models.CharField(blank=True, db_column='CheckerName', max_length=40, null=True)),
                ('checketime', models.DateField(blank=True, db_column='CheckeTime', null=True)),
                ('checkerflag', models.BooleanField(db_column='CheckFlag')),
            ],
            options={
                'db_table': 'PropertyCheck',
            },
        ),
        migrations.CreateModel(
            name='PropertyDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(blank=True, db_column='DeviceId', null=True)),
                ('applier', models.CharField(blank=True, db_column='Applier', max_length=40, null=True)),
                ('applierid', models.IntegerField(blank=True, db_column='ApplierId', null=True)),
                ('appliertel', models.TextField(blank=True, db_column='ApplierTel', null=True)),
                ('datetime', models.CharField(blank=True, db_column='DateTime', max_length=40, null=True)),
                ('damagedepict', models.TextField(blank=True, db_column='damage_depict', null=True)),
                ('photo1', models.TextField(blank=True, db_column='photo_1', null=True)),
                ('photo2', models.TextField(blank=True, db_column='photo_2', null=True)),
                ('photo3', models.TextField(blank=True, db_column='photo_3', null=True)),
                ('photo4', models.TextField(blank=True, db_column='photo_4', null=True)),
                ('photo5', models.TextField(blank=True, db_column='photo_5', null=True)),
                ('photo6', models.TextField(blank=True, db_column='photo_6', null=True)),
                ('voice', models.TextField(blank=True, db_column='voice', null=True)),
                ('schoolid', models.IntegerField(blank=True, db_column='schoolid', null=True)),
                ('devicenum', models.CharField(blank=True, db_column='devicenum', max_length=30, null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=20, null=True)),
                ('deal_status', models.IntegerField(db_column='deal_status', default='0')),
            ],
            options={
                'db_table': 'PropertyDamage',
            },
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolid', models.IntegerField(blank=True, db_column='SchoolId', null=True)),
                ('building', models.CharField(blank=True, db_column='Building', max_length=50, null=True)),
                ('roomname', models.CharField(blank=True, db_column='RoomName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'RoomInfo',
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(db_column='school_name', max_length=40, verbose_name='\u5b66\u6821')),
                ('registnum', models.CharField(blank=True, db_column='registnum', max_length=50, null=True, verbose_name='\u6ce8\u518c\u53f7')),
                ('province', models.CharField(blank=True, db_column='province', max_length=20, null=True, verbose_name='\u7701')),
                ('city', models.CharField(blank=True, db_column='city', max_length=20, null=True, verbose_name='\u5e02')),
                ('county', models.CharField(blank=True, db_column='county', max_length=20, null=True, verbose_name='\u533a/\u53bf')),
                ('longitude', models.FloatField(blank=True, db_column='longitude', null=True, verbose_name='\u7ecf\u5ea6')),
                ('latitude', models.FloatField(blank=True, db_column='latitude', null=True, verbose_name='\u7eac\u5ea6')),
                ('schoolstatus', models.BooleanField(db_column='school_status', default=True, verbose_name='\u72b6\u6001')),
                ('regist_time', models.DateTimeField(db_column='regist_time', null=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
            ],
            options={
                'db_table': 'SchoolInfo',
                'verbose_name_plural': '\u5b66\u6821',
            },
        ),
        migrations.CreateModel(
            name='SeniorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(blank=True, db_column='login_id', max_length=40, null=True, verbose_name='\u767b\u5f55\u8d26\u53f7')),
                ('password', models.CharField(blank=True, db_column='password', max_length=40, null=True, verbose_name='\u767b\u5f55\u5bc6\u7801')),
                ('username', models.CharField(blank=True, db_column='username', max_length=10, null=True, verbose_name='\u59d3\u540d')),
                ('rank', models.CharField(blank=True, db_column='rank', max_length=20, null=True, verbose_name='\u804c\u4f4d')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, verbose_name='Email')),
                ('telephonenum', models.CharField(blank=True, db_column='tel', max_length=20, null=True, verbose_name='\u7535\u8bdd')),
                ('weixin', models.CharField(blank=True, db_column='wechat', max_length=20, null=True, verbose_name='\u5fae\u4fe1')),
                ('qq', models.CharField(blank=True, db_column='qq', max_length=20, null=True, verbose_name='QQ')),
                ('isdelete', models.BooleanField(db_column='status', default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('regist_time', models.DateTimeField(db_column='regist_time', verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('schools', models.ManyToManyField(db_column='schoolid', to='common.SchoolInfo', verbose_name='\u5b66\u6821')),
            ],
            options={
                'db_table': 'SeniorUser',
                'verbose_name_plural': '\u5730\u533a\u5b98\u5458',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(blank=True, db_column='login_id', max_length=40, null=True, verbose_name='\u767b\u5f55\u8d26\u53f7')),
                ('password', models.CharField(blank=True, db_column='password', max_length=40, null=True, verbose_name='\u767b\u5f55\u5bc6\u7801')),
                ('username', models.CharField(blank=True, db_column='username', max_length=10, null=True, verbose_name='\u59d3\u540d')),
                ('job', models.CharField(blank=True, db_column='job', max_length=20, null=True, verbose_name='\u5de5\u4f5c')),
                ('isOfficial', models.BooleanField(db_column='isOfficial', default=False, verbose_name='\u662f\u5426\u662f\u6821\u7ea7\u4ee5\u4e0a\u7684\u7528\u6237')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, verbose_name='Email')),
                ('telephonenum', models.CharField(blank=True, db_column='tel', max_length=20, null=True, verbose_name='\u7535\u8bdd')),
                ('weixin', models.CharField(blank=True, db_column='wechat', max_length=20, null=True, verbose_name='\u5fae\u4fe1')),
                ('qq', models.CharField(blank=True, db_column='qq', max_length=20, null=True, verbose_name='QQ')),
                ('status', models.BooleanField(db_column='status', default=True, verbose_name='\u72b6\u6001')),
                ('regist_time', models.DateTimeField(db_column='regist_time', verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('school', models.ForeignKey(blank=True, db_column='school', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.SchoolInfo', verbose_name='\u6240\u5c5e\u5b66\u6821')),
            ],
            options={
                'db_table': 'User',
                'verbose_name_plural': '\u666e\u901a\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(db_column='typename', max_length=20)),
            ],
            options={
                'db_table': 'usertype',
            },
        ),
        migrations.CreateModel(
            name='ViewRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='userid', null=True)),
                ('viewschool', models.IntegerField(blank=True, db_column='view_school', null=True)),
            ],
            options={
                'db_table': 'ViewRegion',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(db_column='usertype', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.UserType', verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='schoollinkman',
            field=models.ForeignKey(blank=True, db_column='school_linkman', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.User', verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='device',
            name='typeid',
            field=models.ForeignKey(blank=True, db_column='TypeId', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.DeviceType'),
        ),
    ]
